Change font to Novecento Sans Light
cesium/iwq pull request #2
Opened 2020-02-08 19:14 UTC by nelsonmestevao

2020-02-08 20:29 UTC, 0urobor0s requested changes

2020-02-08 20:29 UTC, 0urobor0s commented on main.rb
> +  text = Vips::Image.text(row.fetch("name"), width: 500, dpi: 500, font: 'Novecento Sans Light')
How about changing the font to an environment variable (ENV)?

2020-02-08 20:57 UTC, nelsonmestevao commented on main.rb
> +  text = Vips::Image.text(row.fetch("name"), width: 500, dpi: 500, font: 'Novecento Sans Light')
I think this is so small that a ENV variable it's not the best approach. The best one is a configuration file.

2020-02-09 17:57 UTC, 0urobor0s commented on main.rb
> +  text = Vips::Image.text(row.fetch("name"), width: 500, dpi: 500, font: 'Novecento Sans Light')
Like a `config.yml` file?

2020-02-09 18:02 UTC, nelsonmestevao commented on main.rb
> +  text = Vips::Image.text(row.fetch("name"), width: 500, dpi: 500, font: 'Novecento Sans Light')
Yes, something like that. I am not sure what is the standard config file in ruby though.

2026-03-30 20:10 UTC, closed without merging